<template>
  <details v-if="proposals.length" ref="rootRef" class="sk-group sk-group--proposals" open>
    <summary class="sk-group__head">
      <span class="sk-group__caret">▾</span>
      <span class="sk-group__label">{{ t('cronSkills.proposals.title') }}</span>
      <span class="sk-group__count">{{ proposals.length }}</span>
      <span class="sk-group__meta">{{ t('cronSkills.proposals.meta') }}</span>
    </summary>
    <div class="sk-proposals-list">
      <div v-for="p in proposals" :key="p.proposal_id" class="sk-proposal-row">
        <div class="sk-proposal-row__head">
          <code class="sk-proposal-row__id">{{ p.proposal_id }}</code>
          <span v-if="p.auto_enable_eligible" class="sk-prop-chip sk-prop-chip--ok">{{ t('cronSkills.proposals.gatesOk') }}</span>
          <span v-else class="sk-prop-chip sk-prop-chip--warn">{{ t('cronSkills.proposals.gatesBlocked') }}</span>
          <span
            v-if="typeof p.triggered_by === 'string' && p.triggered_by.startsWith('auto_')"
            class="sk-prop-chip sk-prop-chip--auto"
            :title="t('cronSkills.proposals.autoGeneratedBy', { by: p.triggered_by })"
          >{{ t('cronSkills.proposals.auto') }}</span>
          <span v-if="p.auto_enable && p.auto_enable.status" class="sk-prop-chip sk-prop-chip--warn" :title="p.auto_enable.reason || ''">{{ t('cronSkills.proposals.autoEnableStatus', { status: p.auto_enable.status }) }}</span>
          <span v-if="p.auto_enable && p.auto_enable.validation_profile" class="sk-prop-chip" :title="t('cronSkills.proposals.validationProfile')">{{ p.auto_enable.validation_profile }}</span>
          <span v-if="p.chain_hash" class="sk-prop-hash" :title="t('cronSkills.proposals.chainHash')">{{ String(p.chain_hash).slice(0, 8) }}</span>
        </div>
        <div class="sk-proposal-row__actions">
          <button class="btn btn--ghost btn--sm" type="button" @click="emit('show', p.proposal_id)">{{ t('cronSkills.proposals.show') }}</button>
          <button class="btn btn--primary btn--sm" type="button" :disabled="mutationDisabled" @click="emit('accept', p.proposal_id)">{{ t('cronSkills.proposals.accept') }}</button>
          <button class="btn btn--ghost btn--sm" type="button" :disabled="mutationDisabled" @click="emit('reject', p.proposal_id)">{{ t('cronSkills.proposals.reject') }}</button>
        </div>
      </div>
    </div>
  </details>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { useI18n } from 'vue-i18n'
import type { Proposal } from '@/types/skills'

const { t } = useI18n()

defineProps<{
  proposals: Proposal[]
  mutationDisabled?: boolean
}>()

const emit = defineEmits<{
  show: [proposalId: string]
  accept: [proposalId: string]
  reject: [proposalId: string]
}>()

const rootRef = ref<HTMLElement | null>(null)

defineExpose({
  scrollIntoView(options?: ScrollIntoViewOptions) {
    rootRef.value?.scrollIntoView(options)
  },
})
</script>
