"""Helpers for recording workspace file writes in the active tool context."""

from __future__ import annotations

import hashlib
import re
import subprocess
from fnmatch import fnmatchcase
from pathlib import Path
from typing import Any

from openstarry_code.tools import write_policy
from openstarry_code.tools.types import RetryableToolInputError, current_tool_context

_GENERATED_OR_DERIVED_PATH_PATTERNS = (
    "*.prebuilt",
    "*.generated.*",
    "*.min.*",
    "*.bundle.*",
    "dist/**",
    "build/**",
    "target/**",
    "generated/**",
    "gen/**",
)
_DOCUMENTATION_PATH_PATTERNS = (
    "docs/**",
    "doc/**",
    "documentation/**",
    "manual/**",
    "**/manual/**",
)
_TEST_PATH_PATTERNS = (
    "test/**",
    "tests/**",
    "__tests__/**",
    "**/__tests__/**",
    "*.spec.*",
    "*.test.*",
    "**/*.spec.*",
    "**/*.test.*",
)
_TEST_PATH_REGEX_PATTERNS = (
    re.compile(r"(^|/)test_[^/]+\.[^/]+$", re.I),
    re.compile(r"(^|/)[^/]+_test\.[^/]+$", re.I),
    re.compile(r"(^|/)[^/]*test[^/]*\.(py|js|ts|tsx|rb|php|sh|txt|java|go|zsh)$", re.I),
)
_SCRATCH_ARTIFACT_PATH_REGEX_PATTERNS = (
    re.compile(r"(^|/)(tmp|temp|scratch)(/|$)", re.I),
    re.compile(r"(^|/)\.?(pytest_cache|mypy_cache|ruff_cache|phpunit\.cache)(/|$)", re.I),
    re.compile(
        r"^[^/]*(debug|repro|reproduce|scratch|verify|inspect|investigate)[^/]*"
        r"\.(py|js|ts|rb|php|sh|txt|md|json|yaml|yml|patch|diff|zsh)$",
        re.I,
    ),
    re.compile(r"^[^/]*(debug|repro|reproduce|scratch)[^/]*/", re.I),
    re.compile(r"(^|/)[^/]*\.(patch|diff)$", re.I),
)
_GENERATED_CONTENT_MARKERS = (
    "a bison parser, made by gnu bison",
    "code generated",
    "automatically generated",
    "auto-generated",
    "do not edit",
    "do not modify",
    "generated by",
    "this file was generated",
)
_SCRATCH_ONLY_NUDGE_COUNTS = frozenset({3, 6, 10})
_WORKSPACE_WRITE_PROGRESS_COUNTS = frozenset({1, 3, 6, 10})


def _normalize_relative_path(path: str) -> str:
    normalized = path.replace("\\", "/")
    while normalized.startswith("./"):
        normalized = normalized[2:]
    return normalized.lstrip("/")


def record_workspace_file_write(
    path: Path,
    *,
    operation: str = "write",
    created: bool = False,
) -> None:
    ctx = current_tool_context.get()
    if ctx is None or not ctx.workspace_dir:
        return
    workspace = Path(ctx.workspace_dir).expanduser().resolve()
    try:
        relative_path = path.resolve(strict=False).relative_to(workspace)
    except ValueError:
        return
    ctx.workspace_file_writes.append(
        {
            "path": str(path.resolve(strict=False)),
            "relative_path": relative_path.as_posix(),
            "name": path.name,
            "suffix": path.suffix.casefold(),
            "operation": operation,
            "created": bool(created),
        }
    )


def mutation_ledger_text_hash(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8", errors="replace")).hexdigest()


def snapshot_current_workspace_mutations() -> dict[str, str]:
    ctx = current_tool_context.get()
    if ctx is None or not ctx.workspace_dir:
        return {}
    return snapshot_workspace_mutations(Path(ctx.workspace_dir).expanduser().resolve())


def snapshot_workspace_mutations(workspace: Path) -> dict[str, str]:
    try:
        completed = subprocess.run(
            [
                "git",
                "status",
                "--porcelain=v1",
                "-z",
                "--untracked-files=all",
            ],
            cwd=workspace,
            check=False,
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
        )
    except OSError:
        return {}
    if completed.returncode != 0:
        return {}
    return _parse_git_status_z(completed.stdout.decode("utf-8", errors="replace"))


def record_observed_workspace_mutations(
    *,
    tool_name: str,
    before: dict[str, str],
    metadata: dict[str, Any] | None = None,
) -> None:
    ctx = current_tool_context.get()
    if ctx is None or not ctx.workspace_dir or ctx.on_runtime_event is None:
        return
    after = snapshot_current_workspace_mutations()
    paths = diff_workspace_mutations(before, after)
    if not paths:
        return
    ctx.workspace_mutation_records.append(
        {
            "tool": tool_name,
            "tool_name": tool_name,
            "operation": "observe_only",
            "paths": paths,
            "path_count": len(paths),
            **(metadata or {}),
        }
    )
    event: dict[str, Any] = {
        "feature": "mutation_ledger",
        "name": "workspace_mutation_observed",
        "tool": tool_name,
        "tool_name": tool_name,
        "operation": "observe_only",
        "paths": paths,
        "path_count": len(paths),
        "agent_id": getattr(ctx, "agent_id", None),
        "session_key": getattr(ctx, "session_key", None),
    }
    if metadata:
        event.update(metadata)
    try:
        ctx.on_runtime_event(event)
    except Exception:
        return


def diff_workspace_mutations(
    before: dict[str, str],
    after: dict[str, str],
) -> list[dict[str, str]]:
    paths: list[dict[str, str]] = []
    for relative_path in sorted(set(before) | set(after)):
        before_status = before.get(relative_path)
        after_status = after.get(relative_path)
        if before_status == after_status:
            continue
        paths.append(
            {
                "relative_path": relative_path,
                "status": after_status or "deleted",
                "classification": classify_workspace_path(relative_path),
            }
        )
    return paths


def enforce_workspace_write_deny_effects(
    *,
    tool_name: str,
    before: dict[str, str],
    output: str,
) -> str:
    """Post-execution effect check for the workspace write deny policy.

    Pre-execution screens can only match paths named in tool arguments; a
    command can still mutate a protected path indirectly (for example via a
    helper program it wrote and ran). This check compares git status before
    and after the command; in revert mode it restores protected paths to
    their last committed content and prepends a deny notice to the tool
    output, in warn mode it prepends the notice only. Active when
    OPENSTARRY_CODE_WORKSPACE_WRITE_DENY_EFFECT is warn or revert.
    """

    mode = write_policy.workspace_write_deny_effect_mode()
    if mode == "off":
        return output
    ctx = current_tool_context.get()
    if ctx is None or not ctx.workspace_dir:
        return output
    if not getattr(ctx, "workspace_write_deny_globs", None):
        return output
    workspace = Path(ctx.workspace_dir).expanduser().resolve()
    after = snapshot_workspace_mutations(workspace)
    tracked_only = write_policy.workspace_write_deny_tracked_only()
    violations: list[dict[str, str]] = []
    for entry in diff_workspace_mutations(before, after):
        status = entry["status"]
        if status == "deleted":
            # The path left git status entirely, i.e. it matches HEAD again
            # (or an untracked file is gone) — nothing left to enforce.
            continue
        if tracked_only and status.startswith("??"):
            continue
        relative_path = entry["relative_path"]
        match = write_policy.match_workspace_write_deny(
            workspace / relative_path,
            original_path=relative_path,
            workspace=workspace,
            ctx=ctx,
        )
        if match is None:
            continue
        if tracked_only and not _workspace_path_present_at_head(workspace, relative_path):
            # Tracked-only scopes enforcement to the committed suite. A file
            # the agent created has no HEAD version to protect, and staging it
            # (`git add`) must not turn the creation into a violation: the
            # index is not HEAD, and a revert here would delete the agent's
            # own new file.
            continue
        violations.append({**entry, "pattern": match.pattern})
    if not violations:
        return output
    reverted: list[str] = []
    failures: list[str] = []
    if mode == "revert":
        for violation in violations:
            relative_path = violation["relative_path"]
            if _revert_workspace_path(workspace, relative_path, violation["status"]):
                reverted.append(relative_path)
            else:
                failures.append(relative_path)
    message = _effect_enforcement_message(
        tool_name=tool_name,
        mode=mode,
        violations=violations,
        failures=failures,
        guidance=write_policy._deny_retry_guidance(ctx),
    )
    record: dict[str, Any] = {
        "tool": tool_name,
        "tool_name": tool_name,
        "operation": "effect_enforcement",
        "mode": mode,
        "paths": violations,
        "path_count": len(violations),
        "reverted_paths": reverted,
        "revert_failures": failures,
    }
    ctx.workspace_mutation_records.append(dict(record))
    callback = getattr(ctx, "on_runtime_event", None)
    if callback is not None:
        event: dict[str, Any] = {
            "feature": "workspace_write_deny",
            "name": "effect_enforcement",
            **record,
            "injected_to_model": True,
            "hint_text_sha256": mutation_ledger_text_hash(message),
            "agent_id": getattr(ctx, "agent_id", None),
            "session_key": getattr(ctx, "session_key", None),
        }
        try:
            callback(event)
        except Exception:
            pass
    return f"{message}\n\n{output}"


def _effect_enforcement_message(
    *,
    tool_name: str,
    mode: str,
    violations: list[dict[str, str]],
    failures: list[str],
    guidance: str,
) -> str:
    described = ", ".join(
        f"{violation['relative_path']} (matches {violation['pattern']})"
        for violation in violations
    )
    if mode != "revert":
        return (
            f"[workspace write deny] {tool_name} modified write-protected file(s): "
            f"{described}. These changes violate the workspace write deny policy; "
            f"revert them before finishing.{guidance}"
        )
    if failures:
        revert_note = (
            " The file(s) have been restored to their last committed content, "
            f"except: {', '.join(failures)} (automatic restore failed; revert "
            "those changes yourself)."
        )
    else:
        revert_note = " The file(s) have been restored to their last committed content."
    return (
        f"[workspace write deny] {tool_name} modified write-protected file(s): "
        f"{described}.{revert_note}{guidance} Output below that reports a "
        "successful update to those file(s) is stale; do not rely on it."
    )


def _workspace_path_present_at_head(workspace: Path, relative_path: str) -> bool:
    """Return True when the path has a committed version at HEAD.

    Errors resolve to False: with no HEAD version to restore, enforcement
    (and any revert) is skipped rather than risking deletion of a file the
    agent created.
    """

    try:
        completed = subprocess.run(
            ["git", "ls-tree", "--name-only", "HEAD", "--", relative_path],
            cwd=workspace,
            capture_output=True,
            timeout=10,
        )
    except (OSError, subprocess.SubprocessError):
        return False
    return completed.returncode == 0 and bool(completed.stdout.strip())


def _revert_workspace_path(workspace: Path, relative_path: str, status: str) -> bool:
    target = workspace / relative_path
    if status.startswith("??"):
        try:
            target.unlink(missing_ok=True)
            return True
        except OSError:
            return False
    try:
        completed = subprocess.run(
            ["git", "checkout", "HEAD", "--", relative_path],
            cwd=workspace,
            capture_output=True,
            timeout=10,
        )
    except (OSError, subprocess.SubprocessError):
        return False
    if completed.returncode == 0:
        return True
    # Staged-new paths (e.g. added via `git add`) have no HEAD version to
    # restore; unstage and remove instead. Restricted to paths absent from
    # HEAD so a failed checkout of a HEAD-tracked file is never destructive.
    try:
        ls_tree = subprocess.run(
            ["git", "ls-tree", "--name-only", "HEAD", "--", relative_path],
            cwd=workspace,
            capture_output=True,
            timeout=10,
        )
    except (OSError, subprocess.SubprocessError):
        return False
    if ls_tree.returncode != 0 or ls_tree.stdout.strip():
        return False
    subprocess.run(
        ["git", "rm", "--cached", "-f", "--", relative_path],
        cwd=workspace,
        capture_output=True,
        timeout=10,
        check=False,
    )
    try:
        target.unlink(missing_ok=True)
        return True
    except OSError:
        return False


def classify_workspace_path(relative_path: str) -> str:
    normalized = _normalize_relative_path(relative_path)
    if _path_is_inside_scratch(normalized):
        return "scratch"
    path = Path(normalized)
    if _looks_test_file(normalized):
        return "test-like"
    if _looks_scratch_artifact_path(normalized):
        return "scratch"
    if _matches_any(normalized, _DOCUMENTATION_PATH_PATTERNS):
        return "docs"
    if _looks_generated_or_derived(path, normalized):
        return "generated"
    if normalized:
        return "source"
    return "unknown"


def _parse_git_status_z(output: str) -> dict[str, str]:
    records: dict[str, str] = {}
    entries = output.split("\0")
    index = 0
    while index < len(entries):
        entry = entries[index]
        index += 1
        if not entry:
            continue
        status = entry[:2]
        relative_path = entry[3:] if len(entry) > 3 else ""
        if not relative_path:
            continue
        if status[:1] in {"R", "C"} and index < len(entries):
            relative_path = entries[index] or relative_path
            index += 1
        records[relative_path.replace("\\", "/")] = status
    return records


def record_workspace_file_read(
    path: Path,
    *,
    operation: str = "read",
    offset: int | None = None,
    limit: int | None = None,
    complete: bool | None = None,
) -> None:
    ctx = current_tool_context.get()
    if ctx is None or not ctx.workspace_dir:
        return
    workspace = Path(ctx.workspace_dir).expanduser().resolve()
    try:
        relative_path = path.resolve(strict=False).relative_to(workspace)
    except ValueError:
        return
    resolved = path.resolve(strict=False)
    read_record = {
        "path": str(resolved),
        "relative_path": relative_path.as_posix(),
        "name": path.name,
        "suffix": path.suffix.casefold(),
        "operation": operation,
        "offset": offset,
        "limit": limit,
    }
    if complete is not None:
        read_record["complete"] = bool(complete)
    ctx.workspace_file_reads.append(read_record)
    if complete:
        try:
            ctx.workspace_file_read_state[_read_state_key(resolved)] = {
                "path": str(resolved),
                "relative_path": relative_path.as_posix(),
                "operation": operation,
                **_fingerprint_file(resolved),
            }
        except OSError:
            return


def refresh_workspace_file_read_state(
    path: Path,
    *,
    operation: str = "write",
) -> None:
    ctx = current_tool_context.get()
    if ctx is None or not ctx.workspace_dir:
        return
    workspace = Path(ctx.workspace_dir).expanduser().resolve()
    resolved = path.resolve(strict=False)
    try:
        relative_path = resolved.relative_to(workspace)
    except ValueError:
        return
    try:
        ctx.workspace_file_read_state[_read_state_key(resolved)] = {
            "path": str(resolved),
            "relative_path": relative_path.as_posix(),
            "operation": operation,
            **_fingerprint_file(resolved),
        }
    except OSError:
        return


def require_fresh_workspace_file_read(
    path: Path,
    *,
    tool_name: str,
    original_path: str,
) -> None:
    from openstarry_code.tools.run_mode import full_host_access_active

    if full_host_access_active():
        return
    ctx = current_tool_context.get()
    if ctx is None or not ctx.workspace_dir:
        return
    if not ctx.file_edit_requires_fresh_read:
        return
    workspace = Path(ctx.workspace_dir).expanduser().resolve()
    resolved = path.resolve(strict=False)
    try:
        relative_path = resolved.relative_to(workspace)
    except ValueError:
        return
    if ctx.scratch_dir:
        scratch = Path(ctx.scratch_dir).expanduser().resolve(strict=False)
        try:
            resolved.relative_to(scratch)
            return
        except ValueError:
            pass
    if not resolved.exists():
        return

    key = _read_state_key(resolved)
    state = ctx.workspace_file_read_state.get(key)
    if state is None:
        action = "edit" if tool_name == "edit_file" else "write"
        _record_fresh_read_guard_event(
            ctx=ctx,
            tool_name=tool_name,
            original_path=original_path,
            resolved=resolved,
            relative_path=relative_path.as_posix(),
            reason="missing_fresh_read",
        )
        raise RetryableToolInputError(
            f"{tool_name} must read existing workspace file before modifying it: "
            f"{original_path}. Use read_file without offset or limit, then retry the {action}."
        )

    try:
        current = _fingerprint_file(resolved)
    except OSError as exc:
        _record_fresh_read_guard_event(
            ctx=ctx,
            tool_name=tool_name,
            original_path=original_path,
            resolved=resolved,
            relative_path=relative_path.as_posix(),
            reason="fingerprint_unavailable",
        )
        raise RetryableToolInputError(
            f"{tool_name} could not verify the current file before modifying it: "
            f"{original_path}. Use read_file without offset or limit, then retry."
        ) from exc
    fingerprint_keys = ("size", "sha256")
    if any(state.get(key) != current.get(key) for key in fingerprint_keys):
        _record_fresh_read_guard_event(
            ctx=ctx,
            tool_name=tool_name,
            original_path=original_path,
            resolved=resolved,
            relative_path=relative_path.as_posix(),
            reason="stale_fresh_read",
        )
        raise RetryableToolInputError(
            f"{original_path} changed since it was read. Use read_file without "
            f"offset or limit to refresh context, then retry {tool_name}."
        )


def _record_fresh_read_guard_event(
    *,
    ctx,
    tool_name: str,
    original_path: str,
    resolved: Path,
    relative_path: str,
    reason: str,
) -> None:
    callback = getattr(ctx, "on_runtime_event", None)
    if callback is None:
        return
    event = {
        "feature": "fresh_read_guard",
        "name": "fresh_read_guard.blocked",
        "tool": tool_name,
        "tool_name": tool_name,
        "path": original_path,
        "resolved_path": str(resolved),
        "relative_path": relative_path,
        "reason": reason,
        "outcome": "blocked",
        "agent_id": getattr(ctx, "agent_id", None),
        "session_key": getattr(ctx, "session_key", None),
    }
    try:
        callback(event)
    except Exception:
        return


def record_scratch_file_write(path: Path) -> None:
    ctx = current_tool_context.get()
    if ctx is None or not ctx.scratch_dir:
        return
    scratch = Path(ctx.scratch_dir).expanduser().resolve()
    try:
        relative_path = path.resolve(strict=False).relative_to(scratch)
    except ValueError:
        return
    ctx.scratch_file_writes.append(
        {
            "path": str(path.resolve(strict=False)),
            "relative_path": relative_path.as_posix(),
            "name": path.name,
            "suffix": path.suffix.casefold(),
        }
    )


def scratch_only_progress_note() -> str:
    """Return a compact progress nudge after repeated scratch-only writes."""

    ctx = current_tool_context.get()
    if ctx is None:
        return ""
    scratch_writes = len(getattr(ctx, "scratch_file_writes", []) or [])
    if scratch_writes not in _SCRATCH_ONLY_NUDGE_COUNTS and scratch_writes % 10 != 0:
        return ""
    workspace_writes = len(getattr(ctx, "workspace_file_writes", []) or [])
    if workspace_writes:
        return ""
    return (
        " Note: this turn has written "
        f"{scratch_writes} scratch file(s) and no real workspace file changes yet. "
        "Scratch files are temporary; if the task requires changing the project, "
        "use the scratch findings to edit the actual workspace file(s) before final."
    )


def workspace_write_progress_note() -> str:
    ctx = current_tool_context.get()
    if ctx is None:
        return ""
    workspace_writes = len(getattr(ctx, "workspace_file_writes", []) or [])
    if workspace_writes not in _WORKSPACE_WRITE_PROGRESS_COUNTS and workspace_writes % 10 != 0:
        return ""
    return (
        " Note: workspace changes are now present. Before final, inspect git_diff "
        "and run focused verification for the changed behavior."
    )


def workspace_write_note(path: Path) -> str:
    """Return a short hygiene note for risky workspace write targets."""

    relative_path = _workspace_relative_path(path)
    if relative_path is None:
        return ""

    normalized = _normalize_relative_path(relative_path)
    notes: list[str] = []
    if _looks_generated_or_derived(path, normalized):
        notes.append(
            "generated or derived-looking file; confirm it is a source of truth or "
            "regenerate/verify or remove it before final"
        )
    if _matches_any(normalized, _DOCUMENTATION_PATH_PATTERNS):
        notes.append("documentation file; verify the docs build if retaining this change")
    if _looks_test_file(normalized):
        notes.append(
            "test file; only retain this change if the user explicitly requested "
            "test updates, otherwise move the fix to source files or revert it before final"
        )
    if not notes:
        return ""
    return " (note: " + "; ".join(notes) + ")"


def summarize_workspace_write_notes(paths: list[Path]) -> str:
    """Return one compact note covering a set of workspace write targets."""

    saw_generated = False
    saw_docs = False
    saw_tests = False
    for path in paths:
        relative_path = _workspace_relative_path(path)
        if relative_path is None:
            continue
        normalized = _normalize_relative_path(relative_path)
        saw_generated = saw_generated or _looks_generated_or_derived(path, normalized)
        saw_docs = saw_docs or _matches_any(normalized, _DOCUMENTATION_PATH_PATTERNS)
        saw_tests = saw_tests or _looks_test_file(normalized)

    notes: list[str] = []
    if saw_generated:
        notes.append(
            "generated or derived-looking file(s) changed; confirm they are sources "
            "of truth or regenerate/verify or remove them before final"
        )
    if saw_docs:
        notes.append("documentation file(s) changed; verify the docs build if retaining them")
    if saw_tests:
        notes.append(
            "test file(s) changed; only retain them if the user explicitly requested "
            "test updates, otherwise move the fix to source files or revert them before final"
        )
    if not notes:
        return ""
    return " Note: " + "; ".join(notes) + "."


def summarize_patch_hygiene_warning(paths: list[Path]) -> str:
    """Return an explicit final-diff warning for likely risky changed paths."""

    saw_generated = False
    saw_docs = False
    saw_tests = False
    for path in paths:
        relative_path = _workspace_relative_path(path)
        if relative_path is None:
            continue
        normalized = _normalize_relative_path(relative_path)
        saw_generated = saw_generated or _looks_generated_or_derived(path, normalized)
        saw_docs = saw_docs or _matches_any(normalized, _DOCUMENTATION_PATH_PATTERNS)
        saw_tests = saw_tests or _looks_test_file(normalized)

    notes: list[str] = []
    if saw_generated:
        notes.append(
            "generated or derived-looking file(s) are present in the final diff; "
            "unless those are intentional source-of-truth changes, remove them before final"
        )
    if saw_docs:
        notes.append(
            "documentation file(s) are present in the final diff; verify the docs build "
            "from a clean checkout, and remove them if the task does not require docs "
            "changes; timestamp-only workarounds do not travel with the final patch"
        )
    if saw_tests:
        notes.append(
            "test file(s) are present in the final diff; if the user did not explicitly "
            "ask for test updates, revert them and put the functional change in source files"
        )
    if not notes:
        return ""
    return "[patch_hygiene_warning] " + "; ".join(notes) + "."


def _read_state_key(path: Path) -> str:
    return str(path.resolve(strict=False))


def _fingerprint_file(path: Path) -> dict[str, int | str]:
    stat = path.stat()
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return {
        "size": stat.st_size,
        "mtime_ns": stat.st_mtime_ns,
        "sha256": digest.hexdigest(),
    }


def _workspace_relative_path(path: Path) -> str | None:
    ctx = current_tool_context.get()
    if ctx is None or not ctx.workspace_dir:
        return None
    workspace = Path(ctx.workspace_dir).expanduser().resolve()
    try:
        return path.resolve(strict=False).relative_to(workspace).as_posix()
    except ValueError:
        return None


def _path_is_inside_scratch(normalized: str) -> bool:
    ctx = current_tool_context.get()
    if ctx is None or not ctx.workspace_dir or not ctx.scratch_dir:
        return False
    workspace = Path(ctx.workspace_dir).expanduser().resolve(strict=False)
    scratch = Path(ctx.scratch_dir).expanduser().resolve(strict=False)
    try:
        scratch_relative = scratch.relative_to(workspace).as_posix()
    except ValueError:
        return False
    return normalized == scratch_relative or normalized.startswith(f"{scratch_relative}/")


def _matches_any(path: str, patterns: tuple[str, ...]) -> bool:
    return any(fnmatchcase(path, pattern) for pattern in patterns)


def _looks_generated_or_derived(path: Path, normalized: str) -> bool:
    if _matches_any(normalized, _GENERATED_OR_DERIVED_PATH_PATTERNS):
        return True
    return _has_generated_content_marker(path)


def _looks_test_file(normalized: str) -> bool:
    return _matches_any(normalized, _TEST_PATH_PATTERNS) or any(
        pattern.search(normalized) for pattern in _TEST_PATH_REGEX_PATTERNS
    )


def _looks_scratch_artifact_path(normalized: str) -> bool:
    return any(pattern.search(normalized) for pattern in _SCRATCH_ARTIFACT_PATH_REGEX_PATTERNS)


def _has_generated_content_marker(path: Path) -> bool:
    try:
        if not path.is_file():
            return False
        sample = path.read_text(encoding="utf-8", errors="ignore")[:4096].casefold()
    except OSError:
        return False
    return any(marker in sample for marker in _GENERATED_CONTENT_MARKERS)
