"""Routing policy: pure post-classifier heuristic stages.

The squilla-router step classifies a turn; the policy in this package
decides the final tier from that classification plus turn facts. See
:mod:`openstarry_code.engine.routing.policy` for the stage definitions and the
orchestrating :class:`~openstarry_code.engine.routing.policy.RoutingPolicyEngine`.
"""

from __future__ import annotations

from openstarry_code.engine.routing.calibration import (
    CalibrationState,
    aggregate_calibration,
    apply_bias,
    calibration_path,
    effective_threshold,
    load_calibration,
    save_calibration,
)
from openstarry_code.engine.routing.policy import (
    AntiDowngradeResult,
    BudgetGateInput,
    BudgetGateResult,
    CapabilityGateAction,
    CapabilityGateResult,
    ComplaintUpgradeResult,
    ConfidenceGateResult,
    PolicyInputs,
    PolicyResult,
    ProviderMismatchOutcome,
    ProviderMismatchVeto,
    RoutingDecision,
    RoutingPolicyEngine,
    TierCapability,
    anti_downgrade,
    apply_budget_gate,
    bind,
    budget_gate,
    capability_gate,
    complaint_upgrade,
    confidence_gate,
    detect_complaint,
    large_context_floor,
    large_context_min_tier,
    previous_final_entry,
    previous_final_tier,
    provider_mismatch,
    provider_mismatch_veto,
    reconcile_controller_with_final_tier,
    record_budget_gate_trail,
    record_capability_gate_trail,
    record_provider_mismatch_veto_trail,
    route_class_for_tier,
    tier_for_route_class,
)

__all__ = [
    "AntiDowngradeResult",
    "BudgetGateInput",
    "BudgetGateResult",
    "CalibrationState",
    "CapabilityGateAction",
    "CapabilityGateResult",
    "ComplaintUpgradeResult",
    "ConfidenceGateResult",
    "PolicyInputs",
    "PolicyResult",
    "ProviderMismatchOutcome",
    "ProviderMismatchVeto",
    "RoutingDecision",
    "RoutingPolicyEngine",
    "TierCapability",
    "aggregate_calibration",
    "anti_downgrade",
    "apply_bias",
    "apply_budget_gate",
    "bind",
    "budget_gate",
    "calibration_path",
    "capability_gate",
    "complaint_upgrade",
    "confidence_gate",
    "detect_complaint",
    "effective_threshold",
    "large_context_floor",
    "large_context_min_tier",
    "load_calibration",
    "previous_final_entry",
    "previous_final_tier",
    "provider_mismatch",
    "provider_mismatch_veto",
    "reconcile_controller_with_final_tier",
    "record_budget_gate_trail",
    "record_capability_gate_trail",
    "record_provider_mismatch_veto_trail",
    "route_class_for_tier",
    "save_calibration",
    "tier_for_route_class",
]
