"""Data tables for the post-classifier routing policy.

Moved verbatim from ``engine/steps/squilla_router.py``: the complaint term
list and the large-context floor thresholds are routing-policy inputs, not
step plumbing. Keep them as plain data — the heuristics that consume them
live in :mod:`openstarry_code.engine.routing.policy`.

The complaint list is zh/en only today; that locale gap is intentional and
preserved as-is.
"""

from __future__ import annotations

LARGE_CONTEXT_T2_FLOOR_TOKENS = 25_000
LARGE_CONTEXT_T3_FLOOR_TOKENS = 80_000
LARGE_CONTEXT_T3_CONTEXT_RATIO = 0.40
DEFAULT_CONTEXT_WINDOW_TOKENS = 200_000

THINKING_MODE_ORDER = {"T0": 0, "T1": 1, "T2": 2, "T3": 3}

COMPLAINT_TERMS = (
    "不对",
    "不行",
    "不对劲",
    "还是不对",
    "完全不对",
    "不是这样",
    "你搞错了",
    "你说错了",
    "回答错了",
    "理解错了",
    "搞错重点了",
    "错了",
    "答非所问",
    "没理解",
    "没听懂",
    "太差",
    "太敷衍",
    "敷衍",
    "没用",
    "废话",
    "离谱",
    "乱说",
    "瞎说",
    "胡扯",
    "答得太差",
    "质量太差",
    "不满意",
    "胡说",
    "漏了",
    "遗漏了",
    "没提到",
    "没覆盖",
    "跑题了",
    "偏题了",
    "不是我要的",
    "没按要求",
    "没有按要求",
    "重写",
    "重新来",
    "重新回答",
    "再来一版",
    "换个说法",
    "重新组织",
    "按我说的重来",
    "你没有回答",
    "垃圾",
    "傻逼",
    "sb",
    "蠢",
    "废物",
    "滚",
    "妈的",
    "操",
    "艹",
    "wrong",
    "incorrect",
    "not correct",
    "you are wrong",
    "completely wrong",
    "totally wrong",
    "not what i asked",
    "you misunderstood",
    "that's not right",
    "this is not right",
    "bad answer",
    "terrible answer",
    "awful answer",
    "horrible answer",
    "poor answer",
    "lazy answer",
    "low quality",
    "poor quality",
    "try again",
    "redo",
    "rewrite",
    "start over",
    "answer again",
    "you missed",
    "missed the point",
    "off topic",
    "irrelevant",
    "not helpful",
    "garbage",
    "trash",
    "crap",
    "sucks",
    "stupid",
    "idiot",
    "moron",
    "dumb",
    "pathetic",
    "ridiculous",
    "fuck",
    "fucking",
    "shit",
    "damn",
    "wtf",
    "asshole",
    "bullshit",
    "nonsense",
    "useless",
)
