// @vitest-environment happy-dom

import { afterEach, describe, expect, it } from 'vitest'
import { createApp, nextTick } from 'vue'
import i18n from '@/i18n'
import ChatComposer from './ChatComposer.vue'

afterEach(() => {
  document.body.innerHTML = ''
  i18n.global.locale.value = 'en'
})

describe('ChatComposer AI disclaimer', () => {
  it('keeps the localized provenance and accuracy note next to the composer', async () => {
    const el = document.createElement('div')
    document.body.appendChild(el)
    i18n.global.locale.value = 'en'
    const app = createApp(ChatComposer, {
      modelValue: '',
      'onUpdate:modelValue': () => {},
      attachments: [],
      busySendMode: 'queue',
      hasSendContent: false,
      isStreaming: false,
      isNewLanding: false,
      placeholder: 'Send a message',
      sendButtonTitle: 'Send',
      runMode: 'safe',
      allowedRunModes: ['safe', 'full'],
      modelRoutingMode: 'off',
      modelRoutingSettingsBusy: false,
      routerVisualEffectsEnabled: true,
      codingModeEnabled: false,
      codingModeSettingsBusy: false,
      voiceBusy: false,
      voiceRecording: false,
      voiceReady: true,
    })
    app.use(i18n)
    app.mount(el)
    await nextTick()

    const note = el.querySelector('.chat-ai-disclaimer')
    expect(note?.getAttribute('role')).toBe('note')
    expect(note?.textContent).toBe(
      'Content generated by AI may be inaccurate. For reference only; verify important information.',
    )

    app.unmount()
  })
})
